# Generated by Django 5.0.2 on 2024-07-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promociones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="promociones/")),
            ],
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
    ]
