# Generated by Django 5.0.2 on 2024-03-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("categoria", models.CharField(max_length=50)),
                ("marca", models.CharField(max_length=50)),
                ("stock", models.IntegerField(default=0)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos"),
                ),
                (
                    "valoracion_promedio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("agotado", "Agotado"),
                            ("descontinuado", "Descontinuado"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "precio_original",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_oferta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
