# Generated by Django 5.0.2 on 2024-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen2",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos\\galeria"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen3",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos\\galeria"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen4",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos\\galeria"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen5",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos\\galeria"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="productos\\galeria"
            ),
        ),
    ]
