# Generated by Django 5.0.2 on 2024-03-04 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0003_categoria_alter_producto_valoracion_promedio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos\\galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen2",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos\\galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen3",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos\\galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen4",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos\\galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen5",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos\\galeria",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="vendedor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="productos.vendedor",
            ),
        ),
    ]
