# Generated by Django 5.0.2 on 2024-03-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0004_vendedor_alter_producto_imagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="talla",
            field=models.CharField(default=3, max_length=20),
        ),
    ]
