# Generated by Django 5.0.2 on 2024-03-04 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0005_producto_talla"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio",
        ),
    ]
