# Generated by Django 5.0.2 on 2024-03-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0006_remove_producto_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="producto",
            name="talla",
            field=models.CharField(default=20, max_length=20),
        ),
        migrations.AlterField(
            model_name="producto",
            name="valoracion_promedio",
            field=models.DecimalField(decimal_places=1, default=4.7, max_digits=3),
        ),
    ]
