# Generated by Django 5.0.2 on 2024-03-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0007_alter_producto_stock_alter_producto_talla_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="productos.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos/galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen2",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos/galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen3",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos/galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen4",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos/galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen5",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos/galeria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="productos.vendedor"
            ),
        ),
    ]
