# Generated by Django 5.0.2 on 2024-03-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0009_alter_producto_categoria_alter_producto_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.CharField(default=20, max_length=20),
        ),
        migrations.AlterField(
            model_name="producto",
            name="vendedor",
            field=models.CharField(default=20, max_length=20),
        ),
    ]
