# Generated by Django 5.0.2 on 2024-03-17 17:30

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0010_alter_producto_categoria_alter_producto_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.CharField(
                max_length=100, verbose_name=productos.models.Categoria
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="vendedor",
            field=models.CharField(
                max_length=100, verbose_name=productos.models.Vendedor
            ),
        ),
    ]
