# Generated by Django 5.0.2 on 2024-07-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0012_alter_producto_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos/galeria",
            ),
        ),
        migrations.AddField(
            model_name="vendedor",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="pngegg_3.png",
                null=True,
                upload_to="productos/galeria",
            ),
        ),
    ]
