# Generated by Django 5.0.2 on 2024-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0013_categoria_imagen_vendedor_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio_oferta",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_original",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
