# Generated by Django 5.0.2 on 2024-07-06 03:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0015_category_tags_address_cartorder_cartorderitems_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vendor4",
            new_name="Vendor",
        ),
    ]
