# Generated by Django 5.0.2 on 2024-07-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0016_rename_vendor4_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto_core",
            name="tags",
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="products_status",
            field=models.CharField(
                choices=[
                    ("publicado", "Publicado"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                ],
                default="en revisión",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="qty",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="producto_core",
            name="image",
            field=models.ImageField(
                default="produto.jpg", upload_to="productos/galeria"
            ),
        ),
    ]
