# Generated by Django 5.0.2 on 2024-07-11 16:44

import django.db.models.deletion
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0017_remove_producto_core_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto_core",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productos.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="producto_core",
            name="image",
            field=models.ImageField(
                default="produto.jpg", upload_to=productos.models.user_directory_path
            ),
        ),
    ]
