# Generated by Django 5.0.2 on 2024-07-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0018_producto_core_vendor_alter_producto_core_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
