# Generated by Django 5.0.2 on 2024-07-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0019_category_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="products_status",
            field=models.CharField(
                choices=[
                    ("en_proceso", "Procesando"),
                    ("enviado", "Enviado"),
                    ("devuelto", "Devuelto"),
                    ("en_revision", "En_Revision"),
                    ("publicado", "Publicado"),
                ],
                default="en revisión",
                max_length=20,
            ),
        ),
    ]
